ClickTixWeb/Models/DetalleViewModel.cs
namespace ClickTixWeb.Models
{
    public class DetalleViewModel
    {
        public Pelicula Pelicula { get; set; }
        public List<Funcion> ProximasFunciones { get; set; }

        public List<FuncionStrings> ProximasFuncionesStrings {  get; set; }

        public List<DateOnly> FechasUnicas { get; set; }

        public int? sucursalId { get; set; }
        public string? sucursalNombre { get; set; }
        public List<Sucursal> Sucursales { get; set; }

        public string? CategoriaString { get; set; }
        public string? ClasificacionString { get; set; }


    }
}

ClickTixWeb/Controllers/DetalleController.cs
using ClickTixWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ClickTixWeb.Controllers
{
    public class DetalleController : Controller
    {

        private readonly ClicktixContext _context;
        private readonly ILogger<DetalleController> _logger;


        // GET: DetalleController
        public ActionResult Index()
        {

            return View();
        }
        public DetalleController(ILogger<DetalleController> logger, ClicktixContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult CambioFecha(string fecha, int idPelicula)
        {
            DateOnly fechaSeleccionada = DateOnly.FromDateTime(DateTime.Parse(fecha).Date);

            var turnos = ObtenerTurnosPorFechaYIdPelicula(fechaSeleccionada, idPelicula);



            return PartialView("_TurnosPartial", turnos);
        }

        public IActionResult DetalleUpdate(int peliculaId, int? sucursalId)
        {
            var pelicula = _context.Peliculas.Find(peliculaId);

            if (pelicula == null)
            {
                return RedirectToAction("Index");
            }

            var fechaActual = DateOnly.FromDateTime(DateTime.Now.Date);

            var proximasFuncionesQuery = _context.Funcions
                .Where(f => f.IdPelicula == peliculaId
                            && f.Fecha >= fechaActual
                            && f.Fecha <= fechaActual.AddDays(7)
                            && (!sucursalId.HasValue || _context.Salas.Any(s => s.Id == f.IdSala && s.IdSucursal == sucursalId)))
                .OrderBy(f => f.Fecha)
                .ToList();

            var proximasFuncionesList = proximasFuncionesQuery
                .ToList();

            List<FuncionStrings> ProximasFuncionesStrings = new List<FuncionStrings>();

            var fechasUnicas = _context.Funcions
                .Where(f => f.IdPelicula == peliculaId && f.Fecha >= fechaActual && f.Fecha <= fechaActual.AddDays(7))
                .OrderBy(f => f.Fecha)
                .Where(f => !sucursalId.HasValue || _context.Salas.Any(s => s.Id == f.IdSala && s.IdSucursal == sucursalId))
                .Select(f => f.Fecha)
                .Where(fecha => fecha.HasValue)
                .Select(fecha => fecha!.Value)
                .Distinct()
                .ToList();

            foreach (var funcion in proximasFuncionesList)
            {
                ProximasFuncionesStrings.Add(ObtenerFuncionStrings(funcion.Id));
            }

            var viewModel = new DetalleViewModel
            {
                Pelicula = pelicula,
                ProximasFunciones = proximasFuncionesList,
                FechasUnicas = fechasUnicas,
                ProximasFuncionesStrings = ProximasFuncionesStrings,
                CategoriaString = ObtenerCategoriaPorPeliculaId(peliculaId),
                ClasificacionString = ObtenerClasificacionPorPeliculaId(peliculaId),
            };

            var sucursalesConFunciones = _context.Sucursals
                .Where(sucursal => sucursal.Salas
                    .Any(sala => sala.Funcions
                        .Any(funcion => funcion.IdPelicula == peliculaId)))
                .ToList();
            viewModel.Sucursales = sucursalesConFunciones;

            if (sucursalId.HasValue)
            {
                viewModel.sucursalId = sucursalId;
                viewModel.sucursalNombre = _context.Sucursals
        .Where(s => s.Id == sucursalId)
        .Select(s => s.Nombre)
        .FirstOrDefault();
            }

            return View("Index", viewModel);
        }

        public IActionResult SeleccionarButaca(int funcionId)
        {
            var funcion = _context.Funcions.Find(funcionId);
            var funcionStrings = ObtenerFuncionStrings(funcionId);

            if (funcion == null)
            {
                return RedirectToAction("Index");
            }

            var (filas, columnas) = ObtenerFilasYColumnasPorFuncion(funcionId);

            List<Asiento> asientos = ObtenerAsientosPorFuncion(funcionId);


            var viewModel = new SeleccionButacasViewModel
            {
                Funcion = funcion,
                Filas = filas,
                Columnas = columnas,
                Asientos = asientos,
                FuncionStrings = funcionStrings,
            };

            return View("~/Views/SeleccionButacas/Index.cshtml", viewModel);
        }
        public string ObtenerCategoriaPorPeliculaId(int peliculaId)
        {
            var categoria = _context.Peliculas
               .Where(p => p.Id == peliculaId)
               .Select(p => p.IdCategoriaNavigation.Nombre)
               .FirstOrDefault();

            return categoria;
        }
        public string ObtenerClasificacionPorPeliculaId(int peliculaId)
        {
            var clasificacion = _context.Peliculas
                .Where(p => p.Id == peliculaId)
                .Select(p => p.IdClasificacionNavigation.Clasificacion1)
                .FirstOrDefault();

            return clasificacion;
        }
        public FuncionStrings ObtenerFuncionStrings(int funcionIdABuscar)
        {
            var funcionStrings = (from f in _context.Funcions
                                  join pelicula in _context.Peliculas on f.IdPelicula equals pelicula.Id
                                  join dimension in _context.Dimensions on f.IdDimension equals dimension.Id
                                  join sala in _context.Salas on f.IdSala equals sala.Id
                                  join turno in _context.Turnos on f.TurnoId equals turno.Id
                                  join sucursal in _context.Sucursals on sala.IdSucursal equals sucursal.Id
                                  where f.Id == funcionIdABuscar
                                  select new FuncionStrings
                                  {
                                      Dimension = dimension.Dimension1,
                                      Pelicula = pelicula.Titulo,
                                      Sala = sala.NroSala.ToString(),
                                      Turno = turno.Hora.ToString(),
                                      Idioma = f.IdiomaFuncion,
                                      Sucursal = sucursal.Nombre,
                                      CuitSucursal = sucursal.Cuit.ToString(),
                                      precioFuncion = (double)dimension.Precio,
                                      Fecha = f.Fecha.ToString(),
                                      Id = f.Id
                                  }).FirstOrDefault();


            funcionStrings.Idioma = ObtenerNombreIdioma(funcionStrings.Idioma);

            return funcionStrings;
        }
        public string ObtenerNombreIdioma(string idioma)
        {

            int idiomaId = int.Parse(idioma);

            var nombreIdioma = _context.Idiomas
                .Where(idioma => idioma.Id == idiomaId)
                .Select(idioma => idioma.Idioma1)
                .FirstOrDefault() ?? "Sin idioma";

            return nombreIdioma;
        }

        private List<Turno> ObtenerTurnosPorFechaYIdPelicula(DateOnly fecha, int idPelicula)
        {

            var turnos = _context.Funcions
                .Where(f => f.IdPelicula == idPelicula && f.Fecha == fecha)
                .Select(f => new Turno
                {
                })
                .ToList();

            return turnos;
        }

        public List<Asiento> ObtenerAsientosPorFuncion(int idFuncion)
        {
            List<Asiento> listaAsientos = _context.Asientos
                .Where(a => a.IdFuncion == idFuncion)
                .ToList();

            return listaAsientos;
        }

        public (int Filas, int Columnas) ObtenerFilasYColumnasPorFuncion(int idFuncion)
        {
            var resultado = (from s in _context.Salas
                             join f in _context.Funcions on s.Id equals f.IdSala
                             join a in _context.Asientos on f.Id equals a.IdFuncion
                             where f.Id == idFuncion
                             select new { s.Filas, s.Columnas })
                             .FirstOrDefault();

            return (resultado?.Filas ?? 0, resultado?.Columnas ?? 0);
        }
        // GET: DetalleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DetalleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DetalleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DetalleController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DetalleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DetalleController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DetalleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }

ClickTixWeb/Views/Detalle/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container  mt-4">
@*     <div class="row">
        <div class="col-3">
            <select class="form-select form-select-md" aria-label=".form-select-sm example">
                <option selected>Sucursales</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>
        <div class="col-3">
            <select class="form-select form-select-md" aria-label=".form-select-sm example">
                <option selected>Pelicula</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div>

    </div>
 *@

 @model DetalleViewModel
</div>


<section class="container mt-3 mb-5 ">
                <form method="post" asp-controller="Detalle" asp-action="DetalleUpdate">
                     <input type="hidden" name="peliculaId" value="@Model.Pelicula.Id" />
                     <label for="sucursalId">Selecciona una sucursal:</label>
                     <select name="sucursalId" id="sucursalId">
                        @foreach (var sucursal in Model.Sucursales)
                        {
                            <option value="@sucursal.Id">
                                @sucursal.Nombre
                            </option>
                        }
                    </select>
                    <input type="submit" value="Seleccionar">
                </form> 
                
    @if (!Model.sucursalId.HasValue)
    {
        
                            <h3 class="mb-4 text-center">Por favor, seleccione una sucursal </h3>
    }
    <div class="row shadow p-5 rounded">
        <div class="col-md-4 mb-2 text-center">
            
            <img src="@Model.Pelicula.Portada" alt="Nombre de la Película" class="img-fluid rounded">
                  
        </div>

        <div class="col-md-8 mb-3">
           
            <h2 class="mb-4">@Model.Pelicula.Titulo</h2>
            <p><strong>Género:</strong> @Model.CategoriaString</p>
            <p><strong>Duración:</strong> @Model.Pelicula.Duracion minutos</p>
            <p><strong>Clasificación:</strong> @Model.ClasificacionString</p>
            <p><strong>Descripción:</strong> @Model.Pelicula.Descripcion</p>
            
        </div>
        <hr>
        @{
            var cantidadTabs = Model.FechasUnicas.Count;
        }
        @if (Model.sucursalId.HasValue){
                 <h3 class="mb-4 text-center">Funciones en Clicktix @Model.sucursalNombre</h3>

                <div class="card text-center">
                <div class="card-header p-2">
                            <ul class="nav  nav-pills mb-3" id="pills-tab" role="tablist">
                    @for (int i = 0; i < cantidadTabs; i++)
                    {
                            <li class="nav-item " role="presentation">
                                 <button class="nav-link fw-bolder  mx-1 tab-link text-dar text-dark"   data-bs-toggle="pill" data-bs-target="#pills-@i" type="button" role="tab" aria-controls="pills-@i" aria-selected="@(i == 0)">@Model.FechasUnicas.ElementAt(i).ToString("dd/MM")</button>
                            </li>
                    }
                </ul>
                </div>

                <div class="tab-content " id="pills-tabContent">
                    @if (Model.FechasUnicas != null && Model.FechasUnicas.Any())
        {
                    @for (int i = 0; i < cantidadTabs; i++)
                    {
                                                <div class="tab-pane fade @(i == 0 ? "show active" : "")" id="pills-@i" role="tabpanel" aria-labelledby="pills-tab-@i">
                            @if (Model.ProximasFuncionesStrings != null)
                                {
                                    @foreach (var dimension in Model.ProximasFuncionesStrings
                                                                              .Where(f => f.Fecha.Equals(Model.FechasUnicas.ElementAt(i).ToString()))
                                                                              .Select(f => f.Dimension).Distinct())
                                    {
                                        <div class="card-body" id="turnoContainer">
                                            <div class="row">
                                                <p class="fw-bolder fs-5 text-start">@dimension</p>
                                            </div>
                                            <div class="row">
                                                @if (Model.ProximasFuncionesStrings.Any(f => f.Dimension == dimension && f.Fecha.Equals(Model.FechasUnicas.ElementAt(i).ToString())))
                                                {
                                                    @foreach (var funcion in Model.ProximasFuncionesStrings
                                                                                      .Where(f => f.Dimension == dimension && f.Fecha.Equals(Model.FechasUnicas.ElementAt(i).ToString())))
                                                    {
                                                        if (funcion != null)
            {
                                                        <div class="col-1">
                                                            <form method="post" asp-controller="Detalle" asp-action="SeleccionarButaca">
                                                                <input type="hidden" name="funcionId" value="@funcion.Id" />
                                                                <button class="btn btn-danger text-start btn-auto-width m-1">@funcion.Turno @funcion.Idioma.ToUpper()</button>
                                                            </form>
                                                        </div>
                                                     }}
                                                }
                                                else
                                                {
                                                    <p>No hay funciones disponibles de esta película.</p>
                                                }
                                    </div>
                                </div>
                            }}
                        </div>
                    }}
                </div>
            </div>
        }
        @*         <div class="card text-center">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs" id="dateTabs">
                    @foreach (var funcion in Model.ProximasFunciones)
                    {
                        <li class="nav-item">
                            <a class="nav-link active fw-bolder text-danger" aria-current="true" href="#" data-date="@funcion.Fecha">@funcion.Fecha</a>
                        </li>                    
                    }
                </ul>
            </div>
            @for (int i = 0; i < Model.ProximasFuncionesStrings.Count; i++)
                {
                    var funcionStrings = Model.ProximasFuncionesStrings[i];
                    var funcion = Model.ProximasFunciones[i];

                    <div class="card-body" id="turnoContainer">
                        <div class="row">
                            <p class="fw-bolder fs-5 text-start">@funcionStrings.Dimension</p>
                        </div>
                        <div class="row">
                            <form method="post" asp-controller="Detalle" asp-action="SeleccionarButaca">
                                <input type="hidden" name="funcionId" value="@funcion.Id" />
                                <button class="btn btn-danger text-start btn-auto-width m-1">@funcionStrings.Turno </button>
                            </form>
                        </div>
                    </div>
                }

        </div> *@
    </div>



    










    <div style="height: 100px;">
    </div


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        // Maneja el clic en las pestañas
        $('.tab-link').click(function () {
            // Remueve la clase 'active' de todas las pestañas
            $('.tab-link').removeClass('active');
            // Añade la clase 'active' a la pestaña clicada
            $(this).addClass('active');

            // Agrega estilos adicionales según tus necesidades
            // Por ejemplo, cambiar el color de fondo y el color del texto
            $('.tab-link').css('background-color', '');
            $('.tab-link.active').css('background-color', '#dc3545'); // Color Danger
            $('.tab-link').css('color', '');
            $('.tab-link.active').css('color', '#ffffff'); // Color blanco
        });
    });
</script>

<script>

    $(document).ready(function () {
        $('#dateTabs a').click(function (e) {
            e.preventDefault();

            var date = $(this).data('date');

            cargarTurnos(date);
        });
    });

    function cargarTurnos(fecha) {

        $.ajax({
            url: '/DetalleController/CambioFecha',
            type: 'GET',
            data: { fecha: fecha },
            success: function (data) {
                $('#turnoContainer').html(data);
            },
            error: function () {
                alert('Error al cargar los turnos.');
            }
        });
    }

</script>
</section>