ClickTixWeb/Controllers/CompraController.cs
using ClickTixWeb.Models;
using FirebaseAdmin.Auth;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ClickTixWeb.Controllers
{
    public class CompraController : Controller
    {
        private readonly ClicktixContext _context;
        private readonly ILogger<DetalleController> _logger;
        FirebaseAuth auth = FirebaseAuth.DefaultInstance;


        public CompraController(ILogger<DetalleController> logger, ClicktixContext context)
        {
            _logger = logger;
            _context = context;
        }
        [HttpPost]
        public ActionResult ConfirmarCompra(IFormCollection formCollection)
        {
            var funcionId = int.Parse(formCollection["funcionId"]);
            var precioMomento = decimal.Parse(formCollection["precioMomento"]);
            var email = formCollection["emailHidden"];
            var asientosIds = formCollection["asientosId"].Select(id => int.Parse(id)).ToList();

            Console.WriteLine("-----------------------------------");
            Console.WriteLine("-----------------------------------");
            Console.WriteLine("-----------------------------------");
            Console.WriteLine("-----------------------------------");
            Console.WriteLine(funcionId);
            Console.WriteLine(email);
            Console.WriteLine(precioMomento);
            Console.WriteLine(asientosIds);
            Console.WriteLine("-----------------------------------");
            Console.WriteLine("-----------------------------------");
            Console.WriteLine("-----------------------------------");
            Console.WriteLine("-----------------------------------");

            string UserId = ObtenerUid(email);
            int idAsetear = _context.Tickets.OrderByDescending(ticket => ticket.Id).Select(ticket => ticket.Id).FirstOrDefault();
            string abreviatura = ObtenerAbreviaturaSucursalPorIdFuncion(funcionId, _context);
            foreach (var idAsiento in asientosIds)
            {
                idAsetear++;

                DateTime fechaActual = DateTime.Now;
                var nuevoTicket = new Ticket
                {
                        Id = idAsetear,
                        IdFuncion = funcionId,
                        Fecha = fechaActual,
                        Fila = ObtenerFilaPorId(idAsiento), 
                        Columna = ObtenerColumnaPorId(idAsiento), 
                        PrecioAlMomento = (double)precioMomento,
                        UidFb = UserId,
                        IdLabel = abreviatura + idAsetear.ToString("D10"),
                        IsWithdrawn = false,
                    };
                var entry = _context.Entry(nuevoTicket);
                if (entry.State != EntityState.Detached)
                {
                    entry.State = EntityState.Detached;
                }

                _context.Tickets.Add(nuevoTicket);
            }
            _context.SaveChanges();

            foreach (var asientoId in asientosIds)
            {
                var asiento = _context.Asientos.SingleOrDefault(a => a.Id == asientoId);

                if (asiento != null)
                {
                    asiento.Disponible = 0;
                }
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Home"); 
        }
        public static string ObtenerAbreviaturaSucursalPorIdFuncion(int idFuncion, ClicktixContext dbContext)
        {
            var funcion = dbContext.Funcions
            .Include(f => f.IdSalaNavigation)
                .ThenInclude(s => s.IdSucursalNavigation)
            .FirstOrDefault(f => f.Id == idFuncion);

            if (funcion != null && funcion.IdSalaNavigation != null && funcion.IdSalaNavigation.IdSucursalNavigation != null)
            {
                return funcion.IdSalaNavigation.IdSucursalNavigation.Abreviatura;
            }
            else
            {
                return "";
            }
        }
        public int ObtenerFilaPorId(int asientoId)
        {
            var fila = _context.Asientos
                .Where(asiento => asiento.Id == asientoId)
                .Select(asiento => asiento.Fila)
                .FirstOrDefault();

            return (int)fila;
        }
        public int ObtenerColumnaPorId(int asientoId)
        {
            var fila = _context.Asientos
                .Where(asiento => asiento.Id == asientoId)
                .Select(asiento => asiento.Columna)
                .FirstOrDefault();

            return (int)fila;
        }
        public string ObtenerUid(string email)
        {
            var userRecord = auth.GetUserByEmailAsync(email).Result;

            return userRecord.Uid;

        }

        // GET: CompraController
        public ActionResult Index()
        {
            return View();
        }

        // GET: CompraController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CompraController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CompraController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CompraController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CompraController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CompraController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CompraController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ClickTixWeb/Views/Compra/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model confirmarButacasViewModel;

<!-- Sección -->
<section class="py-5">
    <div class="container row offset-1">

        <div class="mt-3 bg-danger rounded col-6 p-3">
                <form method="post" action="@Url.Action("ConfirmarCompra", "Compra")">    
                      <input type="hidden" name="funcionId" value="@Model.Funcion.Id" />
                      <input type="hidden" name="precioMomento" value="@Model.FuncionStrings.precioFuncion" />
                      <input type="hidden" id="emailHidden" name="emailHidden" />

                    @foreach (var asientoId in Model.AsientosId)
                {
                    <input type="hidden" name="asientosId" value="@asientoId" />
                }
                <div class="row">
                    <!-- Email -->
                    <div class="form-group pt-2" class="text-light">
                        <label for="email" class="text-light">Email:</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Ingrese su email" required>
                    </div>
                    <span class="text-danger" data-valmsg-for="email"></span>
                </div>
                <div class="row">
                    <div class="form-group">
                        <label for="nombreTitular" class="text-light">Nombre de Titular:</label>
                        <input type="text" class="form-control" id="nombreTitular" name="nombreTitular" placeholder="Ingrese el nombre del titular" pattern="[A-Za-z]+" required
                               >
                    </div>
                </div>

                <div class="row">
                    <!-- DNI de Titular -->
                    <div class="form-group">
                        <label for="dniTitular" class="text-light">DNI de Titular:</label>
                        <input type="text" class="form-control" id="dniTitular" placeholder="Ingrese el DNI del titular" pattern="\d{8}" required>
                    </div>
                </div>
                <div class="row">
                    <!-- Número de Tarjeta -->
                    <div class="form-group col-6">
                        <label for="numeroTarjeta" class="text-light">Número de Tarjeta:</label>
                        <input type="text" class="form-control" id="numeroTarjeta" placeholder="Ingrese el número de tarjeta"  required>
                    </div>
                    <!-- Código de Seguridad -->
                    <div class="form-group col-5">
                        <label for="codigoSeguridad" class="text-light">Código de Seguridad:</label>
                        <input type="text" class="form-control" id="codigoSeguridad" placeholder="Ingrese el código de seguridad" pattern="\d{3}" required>
                    </div>
                </div>

                <div class="row">
                    <!-- Fecha de Vencimiento -->
                    <div class="form-group">
                        <label for="fechaVencimiento" class="text-light">Fecha de Vencimiento:</label>
                        <input type="text" class="form-control" id="fechaVencimiento" placeholder="MM/AA"  required>
                    </div>
                </div>

                <div class="row">
                    <!-- Medio de Pago -->
                    <div class="form-group">
                        <label for="medioPago" class="text-light">Medio de Pago:</label>
                        <select class="form-control" id="medioPago" required>
                            <option value="tarjeta">Tarjeta de Crédito</option>
                            <option value="debito">Tarjeta de Débito</option>
                        </select>
                    </div>
                </div>
                <div class="condiciones p-3">
                    <div class="row">
                        <!-- Checkbox 1 -->
                        <div class="form-check">
                            <label class="form-check-label" for="checkbox1"> <p class="text-light">Acepto los términos y condiciones.</p></label>
                            <input type="checkbox" class="form-check-input" id="checkbox1" required>
                        </div>
                    </div>
                    <div class="row">
                        <!-- Checkbox 2 -->
                        <div class="form-check">
                            <label class="form-check-label" for="checkbox2"><p class="text-light">Autorizo el uso de mis datos personales.</p></label>
                            <input type="checkbox" class="form-check-input" id="checkbox2" required>
                        </div>
                    </div>
                </div>
                <!-- Botón de Enviar -->
                <button type="submit" class="btn btn-secondary mt-3" class="text-light">Confirmar Compra</button>
            </form>
        </div>
        <div class="container mt-3 ms-2 p-2 col-5">
            <div class="card p-3 mx-auto" style="max-width: 500px;">
                <div class="col-12 mt-3">
                    <div class="row">
                        <div class="col-6">
                            <img class="card-img-top" src="@Model.portadaDePelicula" alt="Portada de la pelicula (inner necesario)" />
                        </div>
                        <div class="col-6">
                            <div class="row "><h2>@Model.Funcion.Fecha</h2></div>
                            <div class="row"><h4>@Model.FuncionStrings.Pelicula</h4></div>
                            <div class="row"><h4>Hora : @Model.FuncionStrings.Turno</h4></div>
                            <div class="row"><p>Idioma: @Model.FuncionStrings.Idioma</p></div>
                            <div class="row"><p>Dimension: @Model.FuncionStrings.Dimension</p></div>
                            <div class="row"><p>Numero de Sala: @Model.FuncionStrings.Sala</p></div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-6"><p>Numero de Entradas: @Model.AsientosId.Count</p></div
                    <div class="col-6"><p>Precio unitario: $@Model.FuncionStrings.precioFuncion</p></div>

                <div class="row">
                    <div class="ms-2">
                    @for (int i = 0; i < Model.AsientosId.Count; i++)
                    {
                        <p>Fila: @Model.AsientosFilas[i] Columna: @Model.AsientosColumnas[i]</p>
                    }
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-6"><p>SUBTOTAL</p></div>
                    <div class="col-6"><p>$@(Model.AsientosId.Count * Model.FuncionStrings.precioFuncion)</p></div>
                </div>
                <div class="row">
                    <div class="col-6"><p>Cargo por servicio</p></div>
                    <div class="col-6"><p>$@(350 * Model.AsientosId.Count)</p></div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-6"><p>TOTAL:</p></div>
                    <div class="col-6"><p>$@((Model.AsientosId.Count * Model.FuncionStrings.precioFuncion) + (350 * Model.AsientosId.Count))</p></div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-6 text-center"> @Model.FuncionStrings.Sucursal </div>
                    <div class="col-6 text-center"> @Model.FuncionStrings.CuitSucursal</div>
                </div>
            </div>
            </div>

        </div>
    </div>
</section>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    function validarFormulario() {
        // Realiza validaciones adicionales si es necesario

        // Muestra el mensaje de confirmación
        alert("Compra confirmada");
        return true; // Devuelve true para enviar el formulario
    }
</script>
<script>
    $(document).ready(function () {
        var email = localStorage.getItem("email");

        $("#emailHidden").val(email);
    });
</script>