ClickTixWeb/Models/UsuarioWeb.cs
using System;
using System.Collections.Generic;

namespace ClickTixWeb.Models;

public partial class UsuarioWeb
{
    public string? Nombre { get; set; }

    public string? Apellido { get; set; }

    public string? Pass { get; set; }

    public string? Email { get; set; }

    public DateOnly? Fnac { get; set; }

    public string? Genero { get; set; }

    public string? Celular { get; set; }

    public int? SucursalHabitual { get; set; }

    public int IdUsuario { get; set; }

    public virtual Sucursal? SucursalHabitualNavigation { get; set; }
}

ClickTixWeb/Controllers/LoginController.cs
using ClickTixWeb.Models;
using Google.Apis.Auth.OAuth2;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Configuration;
using Microsoft.Extensions.Configuration;
using FirebaseAdmin.Auth;

namespace ClickTixWeb.Controllers
{
    public class LoginController : Controller
    {

        FirebaseAuth auth = FirebaseAuth.DefaultInstance;
        private readonly ClicktixContext _context;
        private readonly IConfiguration _configuration;
        public LoginController(ClicktixContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public string IniciarSesion(string email)
        {
            var uid = ObtenerUidDeUsuario(email); 
            var token = CrearTokenPersonalizado(uid);

            return token;
        }

        private string CrearTokenPersonalizado(Task<UserRecord> uid)
        {
            return "sesion" + uid.ToString();
        }

        private Task<UserRecord> ObtenerUidDeUsuario(string email)
        {
            return auth.GetUserByEmailAsync(email);

        }

        public Boolean verificarEmail(string email)
        {




            if (auth.GetUserByEmailAsync(email).Result == null)
            {

                return false;

            }
            else
            {
                return true;
            }

        }

        public ActionResult Login(string email, string password)
        {



            if (verificarEmail(email))
            {
                ViewData["Token"] = email;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("CuentaError.cshtml");
            }

        }

        private bool UsuarioAutenticado(string email, string password)
        {



            var usuario = _context.UsuarioWebs.FirstOrDefault(u => u.Email == email && u.Pass == password);
            return usuario != null;
        }


       

       
           
        




        public void Metodo()
        {
            var apiKey = _configuration["Firebase:ApiKey"];
            var authDomain = _configuration["Firebase:AuthDomain"];
            var privateKey = _configuration["Firebase:PrivateKey"];

            var credentials = GoogleCredential.FromJson(privateKey);

           
        }

    }
}

ClickTixWeb/Controllers/UsuarioWebsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ClickTixWeb.Models;
using System.Diagnostics;
using FirebaseAdmin.Auth;
using FirebaseAdmin;

namespace ClickTixWeb.Controllers
{
    public class UsuarioWebsController : Controller
    {
        private readonly ClicktixContext _context;

        FirebaseAuth auth = FirebaseAuth.DefaultInstance;

        public UsuarioWebsController(ClicktixContext context)
        {
            _context = context;
        }

        // GET: UsuarioWebs
        public async Task<IActionResult> Index()
        {
            return _context.UsuarioWebs != null ?
                      View(await _context.UsuarioWebs.ToListAsync()) :
                      Problem("Entity set 'ClicktixContext.UsuarioWebs'  is null.");
        }

        // GET: UsuarioWebs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UsuarioWebs == null)
            {
                return NotFound();
            }

            var usuarioWeb = await _context.UsuarioWebs
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuarioWeb == null)
            {
                return NotFound();
            }

            return View(usuarioWeb);
        }

        // GET: UsuarioWebs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UsuarioWebs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUsuario,Nombre,Apellido,Pass,Passc,email,fnac,genero,celular,sucursalHabitual")] UsuarioWeb usuarioWeb)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuarioWeb);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuarioWeb);
        }

        // GET: UsuarioWebs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UsuarioWebs == null)
            {
                return NotFound();
            }

            var usuarioWeb = await _context.UsuarioWebs.FindAsync(id);
            if (usuarioWeb == null)
            {
                return NotFound();
            }
            return View(usuarioWeb);
        }

        // POST: UsuarioWebs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuario,Nombre,Apellido,Pass,Passc,email,fnac,genero,celular,sucursalHabitual")] UsuarioWeb usuarioWeb)
        {
            if (id != usuarioWeb.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuarioWeb);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioWebExists(usuarioWeb.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuarioWeb);
        }

        // GET: UsuarioWebs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UsuarioWebs == null)
            {
                return NotFound();
            }

            var usuarioWeb = await _context.UsuarioWebs
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuarioWeb == null)
            {
                return NotFound();
            }

            return View(usuarioWeb);
        }

        // POST: UsuarioWebs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UsuarioWebs == null)
            {
                return Problem("Entity set 'ClicktixContext.UsuarioWebs'  is null.");
            }
            var usuarioWeb = await _context.UsuarioWebs.FindAsync(id);
            if (usuarioWeb != null)
            {
                _context.UsuarioWebs.Remove(usuarioWeb);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: UsuarioWebs/Login
        public IActionResult Login()
        {
            return View();
        }



        









        // POST: UsuarioWebs/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(string email, string password)
        {
            try
            {
                if (string.IsNullOrEmpty(email) || string.IsNullOrEmpty(password))
                {
                    ViewData["Error"] = "Ingrese correo electrónico y contraseña";
                    return View("Login");
                }

                if (await VerificarEmailAsync(email))
                {
                    ViewData["Token"] = email;
                    // Redirigir al Home si el correo existe

                    if (UsuarioAutenticado(email,password))
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return View("/Views/UsuarioWebs/CuentaError.cshtml");
                    }





                   

                }
                else
                {

                    
                    
                    ViewData["Error"] = "El correo electrónico no existe";
                    return View("/Views/UsuarioWebs/CuentaError.cshtml");
                }
            }
            catch (Exception ex)
            {
                // Loguear o manejar la excepción de alguna manera
                ViewData["Error"] = "Error al intentar iniciar sesión.";
                return View("Login");
            }
        }

        private string ObtenerNombreUsuario(string email)
        {
            var usuario = _context.UsuarioWebs.FirstOrDefault(u => u.Email == email);
            return usuario != null ? $"{usuario.Nombre} {usuario.Apellido}" : string.Empty;
        }
        public IActionResult CerrarSesion()
        {
            // Elimina todos los valores de la sesión
            HttpContext.Session.Clear();

            // O específicamente para un valor:
            // HttpContext.Session.Remove("UsuarioEmail");

            // Redirige a donde sea necesario después de cerrar sesión
            return RedirectToAction("Index", "Home");
        }

        private bool UsuarioWebExists(int id)
        {
            return (_context.UsuarioWebs?.Any(e => e.IdUsuario == id)).GetValueOrDefault();
        }

        private bool UsuarioAutenticado(string email, string password)
        {
            var usuario = _context.UsuarioWebs.FirstOrDefault(u => u.Email == email && u.Pass == password);

            if (usuario != null)
            {
                Console.WriteLine($"Autenticación para {email}: {usuario.Nombre} AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
                return true;
            }

            return false;
        }



        private async Task<bool> VerificarEmailAsync(string email)
        {
            try
            {
                var userRecord = await auth.GetUserByEmailAsync(email);
                return userRecord != null;
            }
            catch (FirebaseAuthException ex)
            {
                // Manejar la excepción de Firebase, puedes loguearla o manejarla de alguna otra manera
                return false;
            }
        }


    }
}

ClickTixWeb/Views/UsuarioWebs/Create.cshtml
@model ClickTixWeb.Models.UsuarioWeb

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UsuarioWeb</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdUsuario" class="control-label"></label>
                <input asp-for="IdUsuario" class="form-control" />
                <span asp-validation-for="IdUsuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pass" class="control-label"></label>
                <input asp-for="Pass" class="form-control" />
                <span asp-validation-for="Pass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fnac" class="control-label"></label>
                <input asp-for="Fnac" class="form-control" />
                <span asp-validation-for="Fnac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SucursalHabitual" class="control-label"></label>
                <input asp-for="SucursalHabitual" class="form-control" />
                <span asp-validation-for="SucursalHabitual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fnac" class="control-label"></label>
                <input asp-for="Fnac" class="form-control" />
                <span asp-validation-for="Fnac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Celular" class="control-label"></label>
                <input asp-for="Celular" class="form-control" />
                <span asp-validation-for="Celular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SucursalHabitual" class="control-label"></label>
                <input asp-for="SucursalHabitual" class="form-control" />
                <span asp-validation-for="SucursalHabitual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ClickTixWeb/Views/UsuarioWebs/CuentaError.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="container mt-5 mb-5" >

            <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Credenciales incorrectas</h5>
                <p class="card-text">Las credenciales proporcionadas son incorrectas. Por favor, inténtelo nuevamente.</p>
                <a href="/login" class="btn btn-danger">Volver al Login</a>
              </div>
            </div>
          </div>
          </div>



</div>


@section scripts {
            <script>

                   localStorage.removeItem("email");
            </script>
}

ClickTixWeb/Views/UsuarioWebs/Delete.cshtml
@model ClickTixWeb.Models.UsuarioWeb

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UsuarioWeb</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fnac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fnac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SucursalHabitual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SucursalHabitual)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fnac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fnac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SucursalHabitual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SucursalHabitual)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdUsuario" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ClickTixWeb/Views/UsuarioWebs/Details.cshtml
@model ClickTixWeb.Models.UsuarioWeb

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UsuarioWeb</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fnac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fnac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SucursalHabitual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SucursalHabitual)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fnac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fnac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Celular)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Celular)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SucursalHabitual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SucursalHabitual)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdUsuario">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ClickTixWeb/Views/UsuarioWebs/Index.cshtml
@model IEnumerable<ClickTixWeb.Models.UsuarioWeb>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fnac)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Celular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SucursalHabitual)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fnac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Celular)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.SucursalHabitual)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fnac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Celular)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.SucursalHabitual)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdUsuario">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.IdUsuario">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdUsuario">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ClickTixWeb/Views/UsuarioWebs/Login.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="">
    <section class="vh-100 gradient-custom">

        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-5 text-center">

                            <div class="mb-md-5 mt-md-4 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                                <p class="text-white-50 mb-5">Ingrese su Usuario y Contraseña</p>

                                <form method="post" asp-controller="UsuarioWebs" asp-action="Login" class="needs-validation" novalidate>
                                    <div class="form-outline form-white mb-4">
                                        <input type="email" id="typeEmailX" class="form-control form-control-lg" name="email" required />
                                        <label class="form-label" for="typeEmailX">Email</label>
                                    </div>

                                    <div class="form-outline form-white mb-4">
                                        <input type="password" id="typePasswordX" class="form-control form-control-lg" name="password" required />
                                        <label class="form-label" for="typePasswordX">Password</label>
                                    </div>

                                    <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Olvidaste tu contraseña?</a></p>

                                    <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
                                </form>
                                <div class="text-danger mt-3">
                                    @ViewData["Error"]
                                </div>
                                <div class="d-flex justify-content-center text-center mt-4 pt-1">
                                    <a href="#!" class="text-white"><i class="fab fa-facebook-f fa-lg"></i></a>
                                    <a href="#!" class="text-white"><i class="fab fa-twitter fa-lg mx-4 px-2"></i></a>
                                    <a href="#!" class="text-white"><i class="fab fa-google fa-lg"></i></a>
                                </div>

                            </div>

                            <div>
                                <p class="mb-0">
                                    No tienes cuenta? <a href="/register" class="text-white-50 fw-bold">Registrate Aqui!</a>
                                </p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div style="height: 200px;"></div>
</div>

@section scripts {
        <script>
            // Example starter JavaScript for disabling form submissions if there are invalid fields
            (function () {
                'use strict';

                window.addEventListener('load', function () {
                    // Fetch all the forms we want to apply custom Bootstrap validation styles to
                    var forms = document.getElementsByClassName('needs-validation');

                    // Loop over them and prevent submission
                    var validation = Array.prototype.filter.call(forms, function (form) {
                        form.addEventListener('submit', function (event) {
                            if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();
        </script>
}